// Generated by CoffeeScript 1.7.1
(function() {
  var DirectoryCopy, fs, mkdirp, path;

  path = require("path");

  fs = require("fs");

  mkdirp = require("mkdirp");

  DirectoryCopy = (function() {
    function DirectoryCopy(input, output, match, exclude) {
      this.input = input;
      this.output = output;
      this.match = match != null ? match : ".*";
      this.exclude = exclude;
      this.reader = require("node-dir");
      this.base = path.resolve(this.input);
      this.getFiles();
    }

    DirectoryCopy.prototype.getFiles = function() {
      return this.reader.files(this.base, (function(_this) {
        return function(err, files) {
          var f, fp, input, output, _i, _len, _results;
          _results = [];
          for (_i = 0, _len = files.length; _i < _len; _i++) {
            f = files[_i];
            fp = path.relative(_this.input, f);
            input = path.resolve(_this.base, f);
            output = path.resolve(process.cwd(), _this.output, fp);
            _results.push(_this.writeFiles(input, output));
          }
          return _results;
        };
      })(this));
    };

    DirectoryCopy.prototype.writeFiles = function(input, output) {
      return fs.readFile(input, {
        encoding: "utf8"
      }, function(err, data) {
        if (typeof data === "undefined") {
          data = "";
        }
        console.log();
        return mkdirp(path.dirname(output), function() {
          return fs.writeFile(output, data, null, function() {
            return console.log("file saved, " + output);
          });
        });
      });
    };

    return DirectoryCopy;

  })();

  exports.DirectoryCopy = DirectoryCopy;

}).call(this);
